# Generated by Django 5.1.9 on 2025-06-17 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_dentista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadocita'),
        ),
        migrations.AddField(
            model_name='invitacionusuario',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica'),
        ),
        migrations.AddField(
            model_name='invitacionusuario',
            name='invitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cita'),
        ),
        migrations.AddField(
            model_name='invitacionusuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rol'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadotratamiento'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
    ]
