# Generated by Django 5.1.9 on 2025-06-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('core', '0003_create_default_entities'),
    ]

    operations = [
    ]
