# Generated by Django 5.1.9 on 2025-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0002_initial_0003_create_default_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionusuario',
            name='ip_creacion',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
