# Generated by Django 5.1.9 on 2025-06-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paciente_email_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
