services:
  docs:
    image: dentisoft_local_docs
    container_name: dentisoft_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./dentisoft:/app/dentisoft:z
    ports:
      - '9000:9000'
    command: /start-docs
